-- local test_link_dao = require "t.dao.test_link_dao"
-- local test_content_dao = require "t.dao.test_content_dao"
-- local test_channel_dao = require "t.dao.test_channel_dao"

-- local test_extract = require "t.util.test_extract"
-- local test_table = require "t.util.test_table"
-- local test_intact = require "t.util.test_intact"
-- local test_wxcrypt = require "t.util.test_wxcrypt"
local test_movie = require "t.util.test_movie"
-- local test_ssdb_content = require "t.ssdb.test_ssdb_content"
